In [1]:
# create an array
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
# numpy version
import numpy as np

print(np.__version__)

1.24.3


In [6]:
# type of
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
# array index
print(arr)
arr[4]

[1 2 3 4 5]


5

In [15]:
# access 2D array
nd_array = np.array([[1,2,3], [9,8,7]])

print(nd_array)

# 2nd row, 3rd column
print(nd_array[1,2])

[[1 2 3]
 [9 8 7]]
7


In [20]:
# 3 dimensional array
nd_array = np.array([[[1,2,3], [9,8,7]], [[10,20,30], [90,80,70]]])

print(nd_array)

print(nd_array[0,1,2])

[[[ 1  2  3]
  [ 9  8  7]]

 [[10 20 30]
  [90 80 70]]]
7


In [25]:
# negative indexing
nd_array = np.array([[1,2,3], [9,8,7]])

print('one before last element : ', nd_array[1,-2])

one before last element :  8


In [37]:
# array slicing
arr = numpy.array([1,2,3,4,5,6])

# from 2nd index to 4th index (include start, exclude end)
print(arr[2:4]) 

# from starting element
print(arr[:4]) 

# until the last element
print(arr[2:]) 

[3 4]
[1 2 3 4]
[3 4 5 6]


In [39]:
# copying an array - no changes to the original arr
copy_arr = arr.copy()
copy_arr[3] = 99

print("Old ", arr)
print("New ", copy_arr)

Old  [1 2 3 4 5 6]
New  [ 1  2  3 99  5  6]


In [40]:
# view an array - changes are made to the original array
view = arr.view()
view[0] = 11

print(arr)
print(view)

[11  2  3  4  5  6]
[11  2  3  4  5  6]


In [41]:
# array reshaping
arr = np.array([[1,2,3], [9,8,7]])
print(arr.shape) 

# result -> 2 dimensions, 3 elements

(2, 3)


In [42]:
# array with 5D using ndmin
arr = np.array([1,2,3,4], ndmin = 5)

print(arr)
print(arr.shape) 

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [48]:
# reshape from 1D to 2D
arr = np.array([1,2,3,4,5,6])
newArr = arr.reshape(3,2)
print(newArr)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
# 1D array iteration 
arr = np.array([1,2,3,4,5,6])

for i in arr:
    print(i)

1
2
3
4
5
6


In [51]:
# 2D array iteration 
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]
